apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-postgres
  labels:
    app: argocd-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-postgres
  template:
    metadata:
      labels:
        app: argocd-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter
          ports:
            - containerPort: 9187
              protocol: TCP
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:postgrespassword@localhost:5432/postgres?sslmode=disable"
---
kind: Service
apiVersion: v1
metadata:
  name: argocd-postgres
spec:
  selector:
    app: argocd-postgres
  type: NodePort
  ports:
    - name: http
      port: 5432
      targetPort: 5432
    - name: exporter
      port: 9187
      targetPort: 9187
