apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-nginx
  labels:
    app: argo-nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: argo-nginx
  template:
    metadata:
      name: argo-nginx-pod
      labels:
        app: argo-nginx
    spec:
      containers:
        - image: nginx:alpine
          name: argo-nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "200Mi"
            limits:
              cpu: "200m"
              memory: "250Mi"
